##################################################
resolver: lts-12.20

##################################################
packages:
- ./genovation-control-pad/

##################################################
extra-deps:
- ../kbd/kbd

- ../spiros/spiros/
- ../enumerate/enumerate
- ../enumerate/enumerate-function

#e.g.
# - git: git@github.com:yesodweb/wai
#   commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
#   subdirs:

##################################################
